name = "Sqrt2Irrational"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Sqrt2Irrational"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
doc.verso = true
[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.25.2"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.25.1"

[[lean_lib]]
name = "Sqrt2Irrational"

[[lean_lib]]
name = "Sqrt2Docs"

[[lean_exe]]
name = "sqrt2docs"
root = "Sqrt2DocsMain"
